In [1]:
import pandas as pd
import numpy as np

In [2]:
#코스피200 항목들 불러오기
코스피200 = pd.read_csv('KOSPI200.csv', encoding='euc-kr')
코스피200.head()

   Unnamed: 0        이름      코드
0           0      삼성전자    5930
1           1    SK하이닉스     660
2           2  삼성바이오로직스  207940
3           3      LG화학   51910
4           4     NAVER   35420

In [3]:
#불러온 종목 코드들을 isin()을 사용하기 위해 리스트형으로 변환 
kospi200 = list(np.array(코스피200['코드'].tolist()))

In [4]:
#투자자 엑셀 파일 불러오기
투자자 = pd.read_csv('투자자20201103.csv', encoding='euc-kr')
투자자.head()

,Unnamed: 0,종목,시가,1,종가1,2,종가2,3,종가3,4,...,프로그램순매수1,프로그램순매수2,프로그램순매수3,프로그램순매수4,프로그램순매수5,프로그램순매수6,프로그램순매수7,프로그램순매수8,프로그램순매수9,프로그램순매수10
0,0,2170,59600,2020-09-08,59600,2020-09-09,59400,2020-09-10,58700,2020-09-11,...,-80.0,177.0,-1568.0,-1345.0,-534.0,948.0,-260.0,-225.0,-516.0,1847.0
1,1,2170,58700,2020-09-11,58300,2020-09-14,59400,2020-09-15,60300,2020-09-16,...,-1345.0,-534.0,948.0,-260.0,-225.0,-516.0,1847.0,-595.0,-462.0,-563.0
2,2,2200,21300,2018-07-16,21600,2018-07-17,21200,2018-07-18,20900,2018-07-19,...,1251.0,-593.0,-1385.0,-1721.0,-486.0,-506.0,-1174.0,-1223.0,-646.0,-360.0
3,3,2200,21700,2018-07-17,21200,2018-07-18,20900,2018-07-19,21800,2018-07-20,...,-593.0,-1385.0,-1721.0,-486.0,-506.0,-1174.0,-1223.0,-646.0,-360.0,-366.0
4,4,2200,21500,2018-07-20,21200,2018-07-23,21800,2018-07-24,20900,2018-07-25,...,-486.0,-506.0,-1174.0,-1223.0,-646.0,-360.0,-366.0,-63.0,46.0,-1646.0

In [5]:
#kospi200 항목들만을 분류해주기
투자자 = 투자자[투자자['종목'].isin(kospi200)]
투자자

,Unnamed: 0,종목,시가,1,종가1,2,종가2,3,종가3,4,...,프로그램순매수1,프로그램순매수2,프로그램순매수3,프로그램순매수4,프로그램순매수5,프로그램순매수6,프로그램순매수7,프로그램순매수8,프로그램순매수9,프로그램순매수10
117,117,2350,10100,2018-07-03,10000,2018-07-04,10000,2018-07-05,10050,2018-07-06,...,-19994.0,-13391.0,-10612.0,6756.0,-7402.0,-11506.0,-26941.0,13628.0,21204.0,3759.0
118,118,2350,9950,2018-07-06,10450,2018-07-09,10400,2018-07-10,10350,2018-07-11,...,6756.0,-7402.0,-11506.0,-26941.0,13628.0,21204.0,3759.0,-32762.0,-36964.0,-12815.0
119,119,2350,10350,2018-07-12,10400,2018-07-13,10500,2018-07-16,10900,2018-07-17,...,13628.0,21204.0,3759.0,-32762.0,-36964.0,-12815.0,-45055.0,-1902.0,-20393.0,16139.0
120,120,2350,9710,2018-09-05,9720,2018-09-06,9730,2018-09-07,9750,2018-09-10,...,-252.0,8237.0,2332.0,-16085.0,578.0,-29398.0,9731.0,17798.0,-7091.0,-25433.0
121,121,2350,9670,2018-09-10,9650,2018-09-11,9640,2018-09-12,9460,2018-09-13,...,-16085.0,578.0,-29398.0,9731.0,17798.0,-7091.0,-25433.0,-18358.0,-11084.0,-8102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250554,1250554,2790,52500,2020-07-09,52600,2020-07-10,51000,2020-07-13,51700,2020-07-14,...,-3550.0,-24849.0,-13143.0,14287.0,-4100.0,-12626.0,-16156.0,-14929.0,18962.0,-36075.0
1250555,1250555,2790,52200,2020-09-02,52100,2020-09-03,52100,2020-09-04,51200,2020-09-07,...,8629.0,-8752.0,-6878.0,-19640.0,-18160.0,-6577.0,-34567.0,-4776.0,-7922.0,-1461.0
1250556,1250556,2790,51000,2020-09-07,50900,2020-09-08,51000,2020-09-09,50300,2020-09-10,...,-19640.0,-18160.0,-6577.0,-34567.0,-4776.0,-7922.0,-1461.0,-55483.0,2897.0,-17017.0
1250557,1250557,2790,51000,2020-09-08,51000,2020-09-09,50300,2020-09-10,50000,2020-09-11,...,-18160.0,-6577.0,-34567.0,-4776.0,-7922.0,-1461.0,-55483.0,2897.0,-17017.0,-4337.0
1250558,1250558,2790,50000,2020-09-11,50500,2020-09-14,51800,2020-09-15,51500,2020-09-16,...,-4776.0,-7922.0,-1461.0,-55483.0,2897.0,-17017.0,-4337.0,-47356.0,-7016.0,-7221.0

In [6]:
#기존코드
#조건에 따라 분류해주기 
기관매수 = 투자자[
            (
                ((투자자.기관순매수1>0) & (투자자.기관순매수2>0)) |
                ((투자자.기관순매수2>0) & (투자자.기관순매수3>0)) |
                ((투자자.기관순매수1>0) & (투자자.기관순매수3>0))
            ) |
            ((투자자.기관순매수1>0) & (투자자.기관순매수2>0) & (투자자.기관순매수3>0))]
기관매수

,Unnamed: 0,종목,시가,1,종가1,2,종가2,3,종가3,4,...,프로그램순매수1,프로그램순매수2,프로그램순매수3,프로그램순매수4,프로그램순매수5,프로그램순매수6,프로그램순매수7,프로그램순매수8,프로그램순매수9,프로그램순매수10
124,124,2350,9070,2019-01-02,9000,2019-01-03,9120,2019-01-04,9410,2019-01-07,...,-475.0,21691.0,49017.0,10945.0,7501.0,25483.0,-3239.0,5688.0,-5571.0,23126.0
125,125,2350,9490,2019-01-07,9560,2019-01-08,9420,2019-01-09,9220,2019-01-10,...,10945.0,7501.0,25483.0,-3239.0,5688.0,-5571.0,23126.0,-8246.0,28382.0,9978.0
126,126,2350,9650,2019-01-08,9420,2019-01-09,9220,2019-01-10,9310,2019-01-11,...,7501.0,25483.0,-3239.0,5688.0,-5571.0,23126.0,-8246.0,28382.0,9978.0,14718.0
127,127,2350,9760,2019-02-28,9590,2019-03-04,9880,2019-03-05,9690,2019-03-06,...,312.0,123365.0,-21695.0,14913.0,-10481.0,9242.0,15962.0,14201.0,14134.0,42459.0
128,128,2350,9710,2019-03-07,9620,2019-03-08,9470,2019-03-11,9480,2019-03-12,...,-10481.0,9242.0,15962.0,14201.0,14134.0,42459.0,200139.0,6521.0,27440.0,-11590.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250547,1250547,2790,64400,2020-03-03,61600,2020-03-04,63000,2020-03-05,64500,2020-03-06,...,11534.0,21193.0,-4561.0,609.0,5167.0,-4982.0,81948.0,45779.0,40481.0,-7175.0
1250548,1250548,2790,63200,2020-03-06,62800,2020-03-09,60500,2020-03-10,61200,2020-03-11,...,609.0,5167.0,-4982.0,81948.0,45779.0,40481.0,-7175.0,-62848.0,-7041.0,-48334.0
1250550,1250550,2790,57000,2020-05-06,56400,2020-05-07,56900,2020-05-08,57700,2020-05-11,...,13878.0,108551.0,9262.0,-19117.0,-9766.0,8515.0,-2803.0,9289.0,-24993.0,10248.0
1250554,1250554,2790,52500,2020-07-09,52600,2020-07-10,51000,2020-07-13,51700,2020-07-14,...,-3550.0,-24849.0,-13143.0,14287.0,-4100.0,-12626.0,-16156.0,-14929.0,18962.0,-36075.0
1250558,1250558,2790,50000,2020-09-11,50500,2020-09-14,51800,2020-09-15,51500,2020-09-16,...,-4776.0,-7922.0,-1461.0,-55483.0,2897.0,-17017.0,-4337.0,-47356.0,-7016.0,-7221.0

##### 설정해주는 조건에 따라 2~3일 연속으로 매수한 경우

In [ ]:
#s는 매수하는 대상 

s = '기관'

#SettingWithCopyWarning: 에러가 발생하여 .copy를 추가해줌
순매수 = 투자자[
    (
                ((투자자.filter(regex = '^{}순매수1$'.format(s))['{}순매수1'.format(s)]>0) & 
                 (투자자.filter(regex = '^{}순매수2$'.format(s))['{}순매수2'.format(s)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수2$'.format(s))['{}순매수2'.format(s)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s))['{}순매수3'.format(s)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수1$'.format(s))['{}순매수1'.format(s)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s))['{}순매수3'.format(s)]>0))
                 |
            ((투자자.filter(regex = '^{}순매수1$'.format(s))['{}순매수1'.format(s)]>0) &
             (투자자.filter(regex = '^{}순매수2$'.format(s))['{}순매수2'.format(s)]>0) & 
             (투자자.filter(regex = '^{}순매수3$'.format(s))['{}순매수3'.format(s)]>0))
    )].copy()

#투자자유형에 따라
#등락률을 넣어준 이유는 이후에 filter를 사용할때 한번에 불러오기 용이하기 위해서 
순매수.loc[:,'등락률_유형'] = s
순매수.rename(columns = {'종목':'종목_등락률'},inplace = True)
순매수

In [ ]:
#매수하는 날짜로부터 10일 이내에 매도할 경우의 등락률 구해주기.
#s_date는 매수 날짜 
s_date = 3

for i in range(10-s_date):
    순매수['등락률'+ str(s_date)+'매수' + str(10-i) +'매도'] = (순매수['종가'+ str(10-i)] - 순매수['종가' + str(s_date)]) / 순매수['종가'+ str(s_date)]

In [ ]:
순매수

In [ ]:
#등락률 포함하는 컬럼만 뽑아주기 (위의 경우 종목 코드와 투자자 유형 그리고 등락률)
등락률 = 순매수.filter(like  = '등락률',axis= 1)

### 종목별로 구해줄 경우

In [ ]:
#종목별 등락률의 평균을 구해줄 경우 
종목별_평균 = 등락률.groupby('종목_등락률',as_index = False).mean()
종목별_평균['투자자 유형'] = 등락률.iloc[0]['등락률_유형']

#컬럼 이름을 다시 원래대로 설정 
종목별_평균.rename(columns = {'종목_등락률':'종목 코드'},inplace = True)

#투자자 유형과 종목 코드를 인덱스로 설정 
종목별_평균 = 종목별_평균.set_index(['투자자 유형','종목 코드'])
종목별_평균

In [ ]:
#최대평균등락률 구해주기
#추후에 행전체를 추출하는 코드 추가 예정 
종목별_평균.idxmax()

In [ ]:
#최소평균등락률 구해주기
종목별_평균.idxmin()

### 종목이 아닌 전체의 등락률을 구하는 경우

In [ ]:
average = pd.DataFrame(columns = ['매수/매도','평균 등락률'])

#종목코드는 필요가 없으므로 
등락률 = 등락률.filter(regex = '매도$')

for each in 등락률.columns:
    average = average.append(pd.DataFrame([[each,등락률[each].mean()]],columns = ['매수/매도','평균 등락률']),ignore_index = True)
    
print(average['평균 등락률'].max())
average

## 함수를 이용하여 모든 투자자유형에 따른 등락률 구해주기(종목별)

In [7]:
#s_type = 투자자 유형
#s_date = 매수날짜 

def get_순매수(s_type,s_date):
    순매수 = 투자자[
    (
                ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
                 |
            ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) &
             (투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0) & 
             (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
    )].copy()
    
    #투자자 유형과 종목코드 설정 
    순매수.loc[:,'등락률_유형'] = s_type
    순매수.rename(columns = {'종목':'종목_등락률'},inplace = True)
    
    #등락률 계산 
    for i in range(10-s_date):
        순매수['등락률'+ str(s_date)+'매수' + str(10-i) +'매도'] = (순매수['종가'+ str(10-i)] - 순매수['종가' + str(s_date)]) / 순매수['종가'+ str(s_date)]
    
    #종목별로 groupby
    등락률 = 순매수.filter(like  = '등락률',axis= 1)
    종목별_평균 = 등락률.groupby('종목_등락률',as_index = False).mean()
    종목별_평균['투자자 유형'] = 등락률.iloc[0]['등락률_유형']

    #컬럼 이름을 다시 원래대로 설정 
    종목별_평균.rename(columns = {'종목_등락률':'종목 코드'},inplace = True)

    #투자자 유형과 종목 코드를 인덱스로 설정 
    종목별_평균 = 종목별_평균.set_index(['투자자 유형','종목 코드'])
    종목별_평균
    return 종목별_평균

In [9]:
#반복문을 이용해주기위해 
투자자_리스트 = ['개인','기관','등록외국','비등록외국','외국계','외국','프로그램']

#반복문안에서 리턴되는 데이터프레임 병합용
final_등락률 = pd.DataFrame()

for each in 투자자_리스트:
    final_등락률 = final_등락률.append(get_순매수(each,3))

In [10]:
final_등락률

               등락률3매수10매도  등락률3매수9매도  등락률3매수8매도  등락률3매수7매도  등락률3매수6매도  \
투자자 유형 종목 코드
개인     70       -0.004262  -0.003239  -0.002075  -0.001082  -0.000206
       80        0.022734   0.018408   0.014227   0.010515   0.006852
       100       0.012369   0.011267   0.010437   0.009071   0.007530
       120       0.006277   0.006584   0.004975   0.003247   0.002482
       150      -0.004823  -0.005752  -0.005605  -0.004629  -0.001618
...                   ...        ...        ...        ...        ...
프로그램   284740    0.001714   0.003351   0.004029   0.003388   0.003040
       285130    0.026293   0.026029   0.021976   0.019386   0.014879
       294870   -0.015946  -0.012970  -0.011317  -0.008015  -0.004359
       316140   -0.013199  -0.010680  -0.008503  -0.007647  -0.007604
       326030   -0.028008  -0.027195  -0.028020  -0.026837  -0.021382

               등락률3매수5매도  등락률3매수4매도
투자자 유형 종목 코드
개인     70      -0.000675  -0.000909
       80       0.004403   0.001680
       100      0.006415   0.003549
       120      0.002465   0.001715
       150     -0.000299   0.001630
...                  ...        ...
프로그램   284740   0.002177   0.000719
       285130   0.011354   0.005438
       294870  -0.002359  -0.000669
       316140  -0.005198  -0.003341
       326030  -0.015344  -0.006917

[1400 rows x 7 columns]

In [37]:
for i in range(7):
    print(final_등락률.loc[final_등락률['등락률3매수{}매도'.format(10-i)].idxmax(),['등락률3매수{}매도'.format(10-i)]])

등락률3매수10매도    0.053806
Name: (비등록외국, 7570), dtype: float64
등락률3매수9매도    0.043493
Name: (비등록외국, 7570), dtype: float64
등락률3매수8매도    0.038099
Name: (개인, 180640), dtype: float64
등락률3매수7매도    0.035133
Name: (비등록외국, 7570), dtype: float64
등락률3매수6매도    0.03103
Name: (비등록외국, 7570), dtype: float64
등락률3매수5매도    0.018624
Name: (비등록외국, 7570), dtype: float64
등락률3매수4매도    0.010382
Name: (개인, 180640), dtype: float64

## 전체의 등락률 구해주기(종목별 X)

In [19]:
def get_avg_순매수(s_type,s_date):
    순매수 = 투자자[
    (
                ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
                 |
                ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) & 
                 (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
                 |
            ((투자자.filter(regex = '^{}순매수1$'.format(s_type))['{}순매수1'.format(s_type)]>0) &
             (투자자.filter(regex = '^{}순매수2$'.format(s_type))['{}순매수2'.format(s_type)]>0) & 
             (투자자.filter(regex = '^{}순매수3$'.format(s_type))['{}순매수3'.format(s_type)]>0))
    )].copy()
    
    #투자자 유형과 종목코드 설정 
    순매수.loc[:,'등락률_유형'] = s_type
    순매수.rename(columns = {'종목':'종목_등락률'},inplace = True)
    
    #등락률 계산 
    for i in range(10-s_date):
        순매수['등락률'+ str(s_date)+'매수' + str(10-i) +'매도'] = (순매수['종가'+ str(10-i)] - 순매수['종가' + str(s_date)]) / 순매수['종가'+ str(s_date)]
    
    average = pd.DataFrame(columns = ['매수/매도','평균 등락률'])
    
    등락률 = 순매수.filter(like  = '등락률',axis= 1)
    등락률 = 등락률.filter(regex = '매도$')

    for each in 등락률.columns:
        average = average.append(pd.DataFrame([[each,등락률[each].mean()]],columns = ['매수/매도','평균 등락률']),ignore_index = True)
    average['투자자유형'] = s_type
    return average

In [38]:
#반복문을 위해 
투자자_리스트 = ['개인','기관','등록외국','비등록외국','외국계','외국','프로그램']

#데이터프레임 병합용
avg_등락률 = pd.DataFrame()

for each in 투자자_리스트:
    avg_등락률 = avg_등락률.append(get_avg_순매수(each,3))
    
avg_등락률 = avg_등락률.set_index('투자자유형')
avg_등락률.sort_values(by = ['평균 등락률'],ascending = False).head()

            매수/매도    평균 등락률
투자자유형
비등록외국  등락률3매수10매도  0.003874
비등록외국   등락률3매수9매도  0.003248
개인     등락률3매수10매도  0.002870
비등록외국   등락률3매수8매도  0.002593
기관     등락률3매수10매도  0.002532